name: autopsy

services:
  container:
    image: quagly/autopsy:latest
    platform: linux/amd64
    build:
      context: .
      shm_size: "2gb"
      tags:
        - quagly/autopsy:0.9.0
        - quagly/autopsy:latest
      platforms:
      - "linux/amd64"
    hostname: autopsy
    container_name: autopsy
    ports:
      - "36901:6901"
      - "35901:5901"
    cap_add:
      - SYS_ADMIN
      - MKNOD
    environment:
      - VNC_RESOLUTION=1920x1080 
      - JAVA_TOOL_OPTIONS=-Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dawt.useSystemAAFontSettings=on
    shm_size: "2gb"
    privileged: true
