name: autopsy

services:
  container:
    image: quagly/autopsy:latest
    platform: linux/amd64
    hostname: autopsy
    container_name: autopsy
    volumes:
      - type: volume
        source: autopsy-data
        target: /home/headless
        read_only: false
      - type: bind
        source: /Users/quagly/data/autopsy 
        target: /home/headless/autopsy/data
        read_only: false 
        bind:
          create_host_path: false
    build:
      context: .
      shm_size: "2gb"
      tags:
        - quagly/autopsy:1.1.0
        - quagly/autopsy:latest
      platforms:
      - "linux/amd64"
    ports:
      - "36901:6901"
      - "35901:5901"
    cap_add:
      - SYS_ADMIN
      - MKNOD
    environment:
      - VNC_RESOLUTION=1920x1080 
      - JAVA_TOOL_OPTIONS=-Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dawt.useSystemAAFontSettings=on
      - DEFAULT_USERDIR_ROOT=/tmp
    shm_size: "2gb"
    privileged: true

volumes:
  autopsy-data:
